language:
  - swift

osx_image: xcode10.2

branches:
  only:
    - master
    - develop

script:
  - xcodebuild -scheme GistsViewer -enableCodeCoverage YES -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.2' build test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -t {$CODECOV_TOKEN}
