language:
  - swift

osx_image: xcode10.2

branches:
  only:
    - master
    - develop

script:
  - xcodebuild -scheme GistsViewerTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.2' test | xcpretty
